### PR TITLE
Debian source package files plus some minor fixes

### PR DESCRIPTION
**Pull request by ryu0**

### CODE REVIEW

**Comment by craftyguy** [comment]
This is really great, thank you for the contribution!

I will review this, but I don't have any way to test that this works for creating a Debian package since I don't use Debian.. do you have a way to demonstrate that it works?

**Comment by ryu0** [comment]
What would you accept as proof? I can build the package and test it but I'm not sure how I would prove that.

**Comment by craftyguy** [comment]
@dario23 since you originally requested the debian package support, would you be able to help test this PR out?

If that doesn't work out, I can probably build a debian VM.

**Comment by craftyguy** [comment]
@ryu0 
I gave it a try in a debian LXC container, and failed horribly. It's probably my own fault though. I followed [the debian manual for building packages](https://www.debian.org/doc/manuals/maint-guide/build.en.html), and failed pretty much immediately:

```
$ debuild                  
 dpkg-buildpackage -rfakeroot -us -uc
dpkg-buildpackage: info: source package networkd-dispatcher
dpkg-buildpackage: info: source version 1.6-1~ppa1
dpkg-buildpackage: info: source distribution xenial
dpkg-buildpackage: info: source changed by Clayton Craft <clayton@craftyguy.net>
 dpkg-source --before-build networkd-dispatcher
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean --parallel --with systemd
   dh_testdir -O--parallel
   dh_auto_clean -O--parallel
	make -j8 clean
make[1]: Entering directory '/home/clayton/networkd-dispatcher'
make[1]: Leaving directory '/home/clayton/networkd-dispatcher'
   dh_clean -O--parallel
 dpkg-source -b networkd-dispatcher
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../networkd-dispatcher_1.6.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -b networkd-dispatcher gave error exit status 255
debuild: fatal error at line 1116:
dpkg-buildpackage -rfakeroot -us -uc failed
```

This error leads me to believe that, typically, debian package metadata stuff is not shipped with the upstream app source code. This is how other distros (e.g. Arch Linux, Gentoo, etc) do it, distro package maintainers maintain the package metadata (e.g. the `debian` subdirectory and all of its contents here in your PR) separately in their own repo(s) and upstream source (e.g. this app hosted on github) is fetched and 'processed' by them when they want to build a new package based on some released version of the upstream app for their distro.

Do you have any examples of upstream applications shipping a similar debian package metadata subdirectory?

Another concern I have is me maintaining all of the stuff under `debian`.. I'm not super motivated to do that since I don't use Debian :)

**Comment by ryu0** [comment]
You got that error because debuild expects to find a tarball contained the original source code of the package in the parent directory of the directory you're building the package in. In my testing I took the tarball of your 1.6 release, recompressed it with xz, and renamed it to networkd-dispatcher_1.6.orig.tar.xz .

If you don't actually want to include the debian packaging additions, would you be open to accepting some commits to reduce how much patching I need to do to make your stuff more compatible with Debian packaging?

**Comment by craftyguy** [comment]
Yea, that makes sense. If the package bootstrapping requires a source archive, then it should not live in the source archive.

> would you be open to accepting some commits to reduce how much patching I need to do to make your stuff more compatible with Debian packaging?

Yes, totally open to including these types of patches!

**Pull request closed without merging**
