### PR TITLE
Fix compatibility with Python 3.4

### PR DESCRIPTION
**Pull request by charles-dyfis-net**
...which sadly still exists in production.

### CODE REVIEW

**Comment by charles-dyfis-net** [comment]
WIP: Doesn't actually work at the moment due to dependency on `os.scandir`. Further commits pending.

**Comment by craftyguy** [comment]
Awesome, thank you very much for the help! 

I don't have any systems with python 3.4, so I will trust that your PR will 'just work' on 3.4. I will test it on 3.6 as well once it is ready.

**Comment by charles-dyfis-net** [comment]
I'm still tracking back some misbehavior, though I suspect it might be unrelated to the Python release -- I'm disabling IPv6LL addresses on several interfaces, and thus am hitting the case where `data['Address']` isn't natively a list. Regardless, if you wanted to wait before merging this, I'll give an all-clear once my QA department has given their thumbs-up.

**Comment by charles-dyfis-net** [comment]
I believe I've confirmed the aforementioned misbehavior to be unrelated to this set of changes, and will be addressing it in a separate PR.

**Comment by charles-dyfis-net** [comment]
(FYI, d2b7cacc090a80ead3cda61a632633e2c003209b merges this PR with the others I've submitted, and is what I'm actually testing in practice).

**Comment by charles-dyfis-net** [comment]
I'm comfortable here.

**Pull request merged**
